// MODULE
import type { Metadata } from 'next'
// COMPONENT
import RecoilRootProvider from '@/util/recoilRootProvider'
// STYLE
import '@style/_index.css'
import Header from '@/component/header'
export const metadata: Metadata = {
  title: "Who's Git",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="UTF-8">
      <body>
        <Header />
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  )
}
