// MODULE
import type { Metadata } from 'next'
// COMPONENT
import RecoilRootProvider from '@/util/RecoilRootProvider'
// STYLW
import './styles/common.css'

export const metadata: Metadata = {
  title: "WHO'S GIT",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="UTF-8">
      <body>
        <RecoilRootProvider>
          {children}
        <RecoilRootProvider /></body>
    </html>
  )
}
